<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1587411205848' stop='1587411232306'>
    <name>Jetpack connection</name>
    <title>Jetpack connection</title>
    <test-cases>
        <test-case start='1587411214676' status='passed' stop='1587411217973'>
            <name>Can find connect button on plugins page</name>
            <title>Can find connect button on plugins page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1587411217973' status='passed' stop='1587411219141'>
            <name>Can find connect button on dashboard page</name>
            <title>Can find connect button on dashboard page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1587411219141' status='failed' stop='1587411232306'>
            <name>Can find connect button on Jetpack page</name>
            <title>Can find connect button on Jetpack page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack connection :: Can find connect button on Jetpack page' source='7eea0bf2-3184-404d-b77b-f00f41b693b0-attachment.png' type='image/png' size='29838'/>
            </attachments>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:40:56)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>